#! /usr/bin/env php

<?php
require 'vendor/autoload.php';
$config = require 'config.php';

use Tumblr\API\Client;
use Symfony\Component\Console\Application;
use seregazhuk\TumblrDownloader\Downloader;
use seregazhuk\TumblrDownloader\SaveCommand;

$client = new Client(
   $config['consumer_key'],
   $config['consumer_secret'],
   $config['token'],
   $config['token_secret']
);

$downloader = new Downloader($client);

$app = new Application('Tumblr Downloader', '1.0');
$app->add(new SaveCommand($downloader));
$app->run();
